"""Pure generation logic: builds docker-compose.yml and Caddyfile."""

from __future__ import annotations

from pathlib import Path

import yaml

from .catalog import CATALOG_BY_KEY


def _is_named_volume(source: str) -> bool:
    return not source.startswith(("/", "./", "$", "~"))


def collect_named_volumes(keys: list[str]) -> list[str]:
    names: list[str] = []
    for key in keys:
        spec = CATALOG_BY_KEY[key]
        for volume in spec.get("volumes", []):
            source = volume.split(":")[0]
            if _is_named_volume(source) and source not in names:
                names.append(source)
    return names


def build_compose(keys: list[str], domain: str) -> dict:
    """Build the docker-compose structure for the selected services."""
    use_proxy = "caddy" in keys and bool(domain)

    services: dict = {}
    for key in keys:
        spec = CATALOG_BY_KEY[key]
        service = {
            "image": spec["image"],
            "container_name": key,
            "restart": "unless-stopped",
        }
        if spec.get("volumes"):
            service["volumes"] = spec["volumes"]
        if spec.get("command"):
            service["command"] = spec["command"]
        if spec.get("ports"):
            service["ports"] = spec["ports"]
        elif spec.get("web") and not use_proxy:
            service["ports"] = spec["host_ports"]
        services[key] = service

    volumes = {name: None for name in collect_named_volumes(keys)}
    compose: dict = {"services": services}
    if volumes:
        compose["volumes"] = volumes
    return compose


def build_caddyfile(domain: str, email: str | None, web_keys: list[str]) -> str:
    """Build a Caddyfile routing subdomains to the selected web services."""
    if not domain:
        return (
            "# No domain configured — automatic HTTPS is disabled.\n"
            ":80 {\n"
            '    respond "zero-to-server is running"\n'
            "}\n"
        )

    blocks: list[str] = []
    if email:
        blocks.append("{\n    email " + email + "\n}")
    for key in web_keys:
        spec = CATALOG_BY_KEY[key]
        blocks.append(
            f"{key}.{domain} {{\n"
            f"    reverse_proxy {key}:{spec['internal_port']}\n"
            f"}}"
        )
    return "\n\n".join(blocks) + "\n"


def to_yaml(compose: dict) -> str:
    return (
        "# Generated by zero-to-server — edit as needed.\n"
        + yaml.safe_dump(compose, sort_keys=False, default_flow_style=False)
    )


def generate(keys: list[str], domain: str, email: str | None, out_dir: str) -> list[str]:
    """Write docker-compose.yml and (optionally) a Caddyfile. Returns written paths."""
    target = Path(out_dir)
    target.mkdir(parents=True, exist_ok=True)

    written: list[str] = []

    compose_path = target / "docker-compose.yml"
    compose_path.write_text(to_yaml(build_compose(keys, domain)), encoding="utf-8")
    written.append(str(compose_path))

    if "caddy" in keys:
        web_keys = [k for k in keys if CATALOG_BY_KEY[k].get("web")]
        caddy_path = target / "Caddyfile"
        caddy_path.write_text(build_caddyfile(domain, email, web_keys), encoding="utf-8")
        written.append(str(caddy_path))

    return written
